### ISSUE TITLE
Supporting Typed Key:Value Pairs for Improved Memory Performance

### ISSUE THREAD

**Issue by atom-moyer** [nnemkin/sparsedict#1]
Hi!

I see that this project has not been updated in quite some time, but I have found it to be the most simple yet fully functional implementation of the google sparsehash that is a drop in replacement for a python dictionary (Correct me if I am wrong, however). Bravo!

Currently, I would like to use this simple dictionary to index Long:Long key value pairs, and I recognize that there is the associated 24*2 bytes of overhead per PyObject stored.  Is there a simple way to enable type definitions of the key value pair which would remove this 48 byte overhead?  Do you have another recommendation for achieving this same goal?

Thanks in advanced,
Adam

**Comment by nnemkin** [comment]
Hi Adam.

Unfortunately, this implementation is a dead end: per-object overhead you mention cancels out any sparsity-related savings. Also, it never went into production and might contain serious bugs.

Unboxing key-value pairs is the right approach, but it won't be easy to achieve in this C implementation.

If the memory saving is truly important and you can afford performance hit due to converting unboxed values to/from PyObjects, I'd suggest to simply wrap an existing C or C++ hash map using Cython or pybind11.

pybind11 in particular has explicit support for automatic binding of STL-compatible maps (`py::bind_map`), you can get a working implementation with just a few lines of code.
